### ISSUE TITLE
new data to share

### ISSUE THREAD

**Issue by BaronPils** [queengooborg/free-dmo-stm32#1]
I have new Tag data maybe nice to add to your collection, I am trying to run the makefile for compiling firmware, but no succes so far.
Made an issue on the main page, maybe you have tips?

**Comment by BaronPils** [comment]
I was able to get it to work, my windows installer was damaged..

**Comment by queengooborg** [comment]
Hi there -- sorry for not responding earlier, I had notifications turned off for this repository on accident!

If you've got tag data you'd like to share, please feel free to upload the dumps here and I'd be happy to get them added in!

**Comment by queengooborg** [comment]
Since this issue isn't actionable without the data, I'm going to go ahead and close it -- but if you've got the data to share, please feel free to post it here or open a new issue!
